logging:
  charset:
    console: UTF-8
    file: UTF-8

spring:
  profiles:
    active: dev

jwt:
  secret: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6  # 秘钥，32位随机字符
  expires-in: 120 # 令牌过期时间，单位秒,这里是为了测试方便，设置得较短，2分钟