# 1. 邮件发送配置（以QQ邮箱为例，需开启SMTP服务并获取授权码）
spring:
  mail:
    host: smtp.qq.com
    port: 587
    username: 2475361850@qq.com  # 发送方邮箱
    password: xljyetzragpdeced # QQ邮箱SMTP授权码（不是登录密码）
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
# 2. 天气API配置（使用「和风天气」免费API，需自行注册获取key）
weather:
  api:
    key: 588beb557b5344cd997afcd0618debb6  # 和风天气API密钥，前面已申请并复制
    city: 101190101					  # 南京的城市ID（可查和风天气城市列表）
    url:  https://n85egkmwk2.re.qweatherapi.com
# 3. 接收邮件列表
email:
  recipients: 2475361850@qq.com  # 多个收件人用逗号分隔